name: Reddit2Instagram

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install modules
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Check
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test
        run: pytest
