name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Check
        run: >
          python -m flake8 . --count --select=E9,F63,F7,F82
          --show-source --statistics

      - name: Test
        run: >
          python -m pytest
          --reddit-client-id ${{ secrets.reddit_client_id }}
          --reddit-client-secret ${{ secrets.reddit_client_secret }}
          --reddit-user-agent "reddit2instagram:GitHubActionsTesting"
